### ISSUE TITLE
Error running program

### ISSUE THREAD

**Issue by DavidDAR1** [naztronaut/dancyPi-audio-reactive-led#31]
pi@raspberrypi:/home/dancyPi-audio-reactive-led/python $ sudo python3 visualization.py scroll

Could not import the PyAudio C module '_portaudio'.
Traceback (most recent call last):
  File "visualization.py", line 7, in <module>
    import microphone
  File "/home/dancyPi-audio-reactive-led/python/microphone.py", line 3, in <module>
    import pyaudio
  File "/usr/local/lib/python3.7/dist-packages/pyaudio.py", line 116, in <module>
    import _portaudio as pa
ImportError: libportaudio.so.2: cannot open shared object file: No such file or directory

Any ideas on how to solve this I am very new to this and not sure what this means stack overflow recommended uninstalling and reinstalling py audio but I am unsure of how to do that through the headless pi

**Comment by naztronaut** [comment]
Try installing libportaudio on the Pi:

```shell
sudo apt install libportaudio2 -y
```

If you want to reinstall pyaudio, you can do:

```shell
sudo pip3 uninstall pyaudio
sudo pip3 uninstall pyaudio
```

If that doesn't work, what kind of Mic are you using?

**Comment by DavidDAR1** [comment]
It appears to have worked with sudo apt install libportaudio2 -y

Does this look right?
pi@raspberrypi:/home/dancyPi-audio-reactive-led/python $ sudo python3 visualization.py scroll
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
FPS 48 / 50
FPS 47 / 50
FPS 46 / 50
FPS 46 / 50
FPS 46 / 50
FPS 46 / 50
FPS 47 / 50
FPS 48 / 50
FPS 46 / 50

**Comment by DavidDAR1** [comment]
The mic I am using:
https://www.amazon.com/gp/product/B08J4G31BZ/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1

I believe it runs at 192kHz would that be the issue or wiring?
Also how would I change the file config.py for 300 leds and if I need to for the mic rate

**Comment by DavidDAR1** [comment]
New update: The lights are turning on and off randomly throughout the strip. It seems like it might be sound activated but no real coordination. Sometimes it is a string of 5 of them together and others it is the whole strip.

**Comment by DavidDAR1** [comment]
Another note: I ran cat /proc/asound/cards and it returned

 0 [b1             ]: bcm2835_hdmi - bcm2835 HDMI 1
                      bcm2835 HDMI 1
 1 [Headphones     ]: bcm2835_headphonbcm2835 Headphones - bcm2835 Headphones
                      bcm2835 Headphones
 2 [Device         ]: USB-Audio - Usb Audio Device
                      Generalplus Usb Audio Device at usb-3f980000.usb-1.1.2, full speed

I have unplugged device 1 being the headphone jack in the aux port could the issue be that device 2 is my mic and it is supposed to be 1? How would I update this in asound.conf and also the number of leds?

**Comment by naztronaut** [comment]
Can you unplug the headphones, restart, and try that command again?

If your  USB device is still device 2, edit `/etc/asound.conf`, find the two lines where it says `card 1` and change it to `card 2`. 

Then edit file `/usr/share/alsa/alsa.conf` and find the two following lines and change the `1` to `2`:

```
defaults.ctl.card 1
defaults.pcm.card 1
```

Then try again.

**Comment by DavidDAR1** [comment]
I updated it to use sound card 2 and it is running the same as before random and erratic lights that change slowly. The fps is only hitting 10/50 what could be the cause of that? I also edited the led to be =300 instead of the original 144 and left the mic rate at 48000

**Comment by naztronaut** [comment]
How are you powering the lights? Through your Pi or are you using an external power source? And which Pi are you using? Pi 3?

**Comment by DavidDAR1** [comment]
It is a pi 3b. The lights have an external power source and the live wire goes directly into the lights. The ground from the power cord originally went into the pi and then another pi ground was run to the lights. Currently I have the ground split from the power one side running to the lights and the other running to the pi.

**Comment by DavidDAR1** [comment]
![IMG_6730](https://user-images.githubusercontent.com/76077109/102300426-8a7bc980-3f1a-11eb-8a26-85705ddee662.jpg)
![IMG_6738](https://user-images.githubusercontent.com/76077109/102300430-8ea7e700-3f1a-11eb-9d56-a4a5815e9e2c.jpg)
![IMG_6737](https://user-images.githubusercontent.com/76077109/102300433-9071aa80-3f1a-11eb-807f-cce9e8e82cca.jpg)

**Comment by naztronaut** [comment]
The wiring looks good. How many amps is the Power source? And how about the power source for your Pi? The low FPS generally points to something on the pi not being able to compute the data fast enough, which I usually found relates to low power issues. 

Let's test your lights with a script someone else created (I'll integrate it into my project at some point). To get the file into your Pi, do:
```
sudo wget https://raw.githubusercontent.com/jgarff/rpi_ws281x/master/python/examples/strandtest.py
```

Then run:
```
sudo python3 strandtest.py
```

See if that runs. It'll at least rule out any issues with the lights themselves. This script is far less process-heavy than the audio reactive piece because it just runs the lights without input.

**Comment by DavidDAR1** [comment]
The led strip power source is 5 volts and 10 amps at 100 watts. The raspberry pi has a power source of 5 volts 3 amps. I will try that out now to test the lights! Appreciate the help its been a learning project for sure!!

**Comment by naztronaut** [comment]
Happy to help! 

That should be more than enough power. So it's weird why yours seems to stutter. For comparison, I'm also running this on a Pi 3b and my strip has 144 LEDs and I power it directly from the Pi and get about 40-50 FPS. 

It *could* be the mic. You said that its rate goes from 20Hz to 20kHz, I think the frequency is different from the sample rate. The sample rate normally ranges from 8kHz to 192kHz. The most common are 48kHz (default for this app) and 44.1kHz (so you could also try 44100 as the rate and see if that helps). 

You'd update the `MIC_RATE` in `config.py` and see what the script says. You could try a few ranges and see if they work. 

Can you also post a link to the LED strip that you bought? You May have done this on YouTube, I can look that up (GitHub is just better for me sometimes :) ).

**Comment by DavidDAR1** [comment]
BTF-LIGHTING WS2812B RGB 5050SMD Individual Addressable 16.4FT 60Pixels/m 300Pixels Flexible Black PCB Full Color LED Pixel Strip Dream Color IP30 Non-Waterproof Making LED Screen LED Wall Only DC5V https://www.amazon.com/dp/B01CDTEJBG/ref=cm_sw_r_cp_api_glc_i_bmz2FbP88AK00?_encoding=UTF8&psc=1


USB Microphone for Computer,... https://www.amazon.com/dp/B08J4G31BZ?ref=ppx_pop_mob_ap_share


ALITOVE 5V 10A Power Supply... https://www.amazon.com/dp/B0852HL336?ref=ppx_pop_mob_ap_share



I played around with the mic and also plugged it into my laptop it said 44100 and 48000 so I changed it on my laptop from where it was at 44100 to 4800 and tried both on the raspberry pin as well. I am not sure what the issue is with the FPS being so low and also the the led strip not lighting up with the simpler program you provided. I think I’m gonna buy a shorter strip and see if I can get it to work and then come back to this! Really enjoyed this tutorial though I’ll keep looking for a way to make this led strip work let me know if you have any ideas! :)

**Comment by naztronaut** [comment]
All the materials look good. Let me know if you get a chance to run that stdrandtest.py script. It'll be a good troubleshooting step. 

Glad you liked the tutorial! I'm actually working on an update to this one where a Mic isn't necessary.  You can play an MP3 off your Pi Directly (it actually also works with any media, like playing a song from YouTube - and could work with Spotify, need to test it). 

I'm planning on releasing that video on Friday. It's still a work-in-progress so it'll be considered version 1.0 until I can work out all the kinks. You could try that out as well when I'm done with it. It'll be in a separate branch for now.

**Comment by DavidDAR1** [comment]
Sounds awesome I’ll check that out! The strandtest.py was only light up the first 5 led’s from the power input on the strip so I assume that has something to do with what’s going on

**Comment by naztronaut** [comment]
Edit `strandtest.py` and change the `LED_COUNT` from 16 to 300 (on like 13 I believe). Sorry, should have mentioned that edit earlier. 

But 5 LEDs isn't normal, it should at least do the first 16. But maybe there's something weird happening. Change the LED count and see if that helps.

**Comment by DavidDAR1** [comment]
Well I did that and all of a sudden that worked fine. Then I ran the project and BOOM works fine! Steady 50 fps too. Not sure what happened but I did unplug everything for several hours when I packed it up. Maybe to many processes were going on for the  pi to handle and restarting ended all the unnecessary ones but anyway I guess it is resolved hopefully no new issues arise! I really want to thank you for responding with lightning speed! Amazing creator!

**Comment by naztronaut** [comment]
Awesome! It's the old "turn it off and turn it back on" trick. 

Glad things are working :) Have fun with the project!

**Comment by maxreus909** [comment]
Hi Nazmus Nasir, 
I am Maxreus909. 
what could be the error,  when I am playing any music on Pi. It still shows only FPS 21/50 and that's in all music. Could you please help me ?

pi@raspberrypi:~ $ cd dancyPi-audio-reactive-led/python
pi@raspberrypi:~/dancyPi-audio-reactive-led/python $ sudo python3 visualization.py scroll_in
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_a52.c:823:(_snd_pcm_a52_open) a52 is only for playback
ALSA lib conf.c:5014:(snd_config_expand) Unknown parameters {AES0 0x6 AES1 0x82 AES2 0x0 AES3 0x2  CARD 0}
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM iec958:{AES0 0x6 AES1 0x82 AES2 0x0 AES3 0x2  CARD 0}
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_dmix.c:1043:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:1043:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:1043:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:1086:(snd_pcm_dmix_open) unable to create IPC shm instance
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
No audio input. Volume below threshold. Volume: 9.9551e-17
FPS 21 / 50
FPS 21 / 50
FPS 21 / 50
FPS 21 / 50
FPS 21 / 50
FPS 21 / 50

**Comment by naztronaut** [comment]
Hi Max, can you do what David did above and unplug everything, wait a bit, and then plug everything back in? In case it's some weird thing. 

You can also run a test for the lights to rule out the lights being an issue. I mentioned it above: https://github.com/naztronaut/dancyPi-audio-reactive-led/issues/31#issuecomment-745740564
